title: "Klaraval Site"
description: "Din beskrivning här"
baseurl: "/Klaraval-site" # OBS! exakt samma versaler/gemener som repo-namnet
url: "https://morandasings.github.io"

# Andra inställningar du behöver
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
